---
title: "STA426_exercise1_part_2"
author: "almut"
date: "17 September 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##Aim: 
Exercise to get used with Rmarkdowns and knir routines

load packages 
```{r packages, warning=FALSE, message=FALSE}
library(ggplot2)
```


## Data
Sample 100 values from a log normal distribution (mu =1, sigma=0.25)

```{r sample data}
log_norm <- rlnorm(100, meanlog = 1, sdlog = 0.25)
mean_log <- mean(log_norm)
var_log <- var(log_norm)
```

The mean of my sampled data is `r mean_log` and the variance is `r var_log`

## Histogram
**A) Plot the sampled data in a histogram**
```{r histogram}
#create a histogram and plot it
hist <- hist(log_norm, breaks=seq(0, 6, by = 0.5), col= "darkblue")
```
  
**B) Plot the sampled data in a histogram on log scale**   
Ignore warnings caused by bins with 0 counts  
```{r log scale plot, warning=FALSE, tidy=TRUE}
#plot data in a histogram on a log scale using ggplot (needs to be converted into data frame first)

ggplot(as.data.frame(log_norm), aes(log_norm)) + geom_histogram(col="darkblue",fill ="blue", alpha = .2, breaks=seq(0, 6, by = 0.5)) + scale_y_log10() 

```